spring:
  application:
    name: auto-trade

  datasource:
      url: jdbc:postgresql://localhost:5434/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: validate
    properties:
        hibernate:
    show-sql: true
    open-in-view: false
server:
  servlet:
    context-path: /v1/auto-trade
